services:
  parser_service:
    build:
      context: ./parser-service
      dockerfile: Dockerfile
    image: parser-service:latest
    container_name: parser_service
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OTHER_ENV=${OTHER_ENV}
      - SELENIUM_URL=${SELENIUM_URL}
      - DRIVER_POOL_SIZE=${DRIVER_POOL_SIZE}
      - SELENIUM_REMOTE=${SELENIUM_REMOTE}
      - DRIVER_CREATE_RETRIES=${DRIVER_CREATE_RETRIES}
      - DRIVER_CREATE_RETRY_DELAY=${DRIVER_CREATE_RETRY_DELAY}
      - DRIVER_IMPLICIT_WAIT=${DRIVER_IMPLICIT_WAIT}
    ports:
      - "8000:80"
    # В dev: можно монтировать только исходники parser-service (если хотите live edit)
    volumes:
      - ./parser-service:/usr/src/app
    depends_on:
      - db
      - selenium
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - kafka-network

  api_gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    container_name: api_gateway
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - ./api-gateway/src:/usr/src/app
    depends_on:
      - parser_service
    restart: unless-stopped
    networks:
      - kafka-network

  new_service:
    build:
      context: ./new-service
      dockerfile: Dockerfile
    image: new-service:latest
    container_name: new_service
    env_file: .env
    ports:
      - "8001:80"
    volumes:
      - ./new-service/src:/usr/src/app
    restart: unless-stopped
    networks:
      - kafka-network

  db:
    image: postgres:14
    container_name: fastapi_db
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - kafka-network

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium_chrome
    shm_size: '2gb'
    ports:
      - "4444:4444"
    restart: unless-stopped
    environment:
      - SE_NODE_MAX_SESSIONS=20
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_SESSION_RETRY_INTERVAL=1
      - SE_SESSION_REQUEST_TIMEOUT=300
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/wd/hub/status" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - kafka-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/commands/ruok || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    restart: unless-stopped
    volumes:
      - ./create-topics.sh:/create-topics.sh
    entrypoint: [
      "/bin/sh",
      "-c",
      "chmod +x /create-topics.sh && sleep 20 && /create-topics.sh & /etc/confluent/docker/run"
    ]
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

volumes:
  db_data:
