services:
  app:
    build:
      context: .
    volumes:
      - ./app:/usr/src/app/app   # монтируем код, чтобы видеть изменения
    command: >
      bash -c "pip install --no-deps -r /usr/src/app/app/requirements.txt || true &&
               uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
    ports:
      - "8000:80"
    environment:
      - PYTHONUNBUFFERED=1
