services:
  app:
    build: .
    image: fastapi-app:latest
    container_name: fastapi_app
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OTHER_ENV=${OTHER_ENV}
    ports:
      - "8000:80"   # внешний порт 8000 -> внутренний 80
    volumes:  # TODO: на проде удалить
      - .:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload  # TODO: на проде удалить
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  db:
    image: postgres:14
    container_name: fastapi_db
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: "no"
    # restart: unless-stopped  TODO: НА ПРОДЕ РАСКОМЕННИРОВАТЬ

volumes:
  db_data:
